default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: <%= ENV.fetch("EECSHELP_DATABASE_HOST", "localhost") %>
  database: <%= ENV.fetch("EECSHELP_DATABASE", "eecshelp_development") %>
  username: <%= ENV.fetch("EECSHELP_DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("EECSHELP_DATABASE_PASSWORD", "1nc0rr3ct") %>

test:
  <<: *default
  host: <%= ENV.fetch("EECSHELP_TEST_DATABASE_HOST", "localhost") %>
  database: <%= ENV.fetch("EECSHELP_TEST_DATABASE", "eecshelp_test") %>
  username: <%= ENV.fetch("EECSHELP_TEST_DATABASE_USERNAME", "root") %>
  password: <%= ENV.fetch("EECSHELP_TEST_DATABASE_PASSWORD", "1nc0rr3ct") %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>